name: Build

on:
  push:
  release:
    types: [published]

jobs:
  athena:
    name: Build for Athena
    runs-on: ubuntu-22.04
    steps:
      # Job setup & initial build
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Setup Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - name: "Release: Get version number"
        id: get_version
        if: github.event_name == 'release'
        uses: battila7/get-version-action@v2
      - name: "Release: Get release info"
        id: get_release_info
        if: github.event_name == 'release'
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Upload vendordep
      - name: "Release: Generate vendordep"
        if: github.event_name == 'release'
        run: bazelisk build --define "publishing_version=${{ steps.get_version.outputs.version-without-v }}" //:vendordep
      - name: "Release: Upload vendordep"
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: bazel-bin/AdvantageKit.json
          asset_name: AdvantageKit.json
          asset_content_type: application/json

      # Upload example projects
      - name: "Release: Generate example projects"
        if: github.event_name == 'release'
        run: bazelisk build --define "publishing_version=${{ steps.get_version.outputs.version-without-v }}" //example_projects
      - name: "Release: Upload example project (skeleton)"
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: bazel-bin/example_projects/skeleton.zip
          asset_name: AdvantageKit_SkeletonProject.zip
          asset_content_type: application/zip
      - name: "Release: Upload example project (diff_drive)"
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: bazel-bin/example_projects/diff_drive.zip
          asset_name: AdvantageKit_DiffDriveProject.zip
          asset_content_type: application/zip
      - name: "Release: Upload example project (swerve_drive)"
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: bazel-bin/example_projects/swerve_drive.zip
          asset_name: AdvantageKit_SwerveDriveProject.zip
          asset_content_type: application/zip
